### ISSUE TITLE
Container start fails

### ISSUE THREAD

**Issue by MiguelElGallo** [pamelafox/simple-fastapi-container#42]
When using the container version, within Visual Studio code in MAC M2, the following error shows:

`An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
Check the log at /home/vscode/.cache/pre-commit/pre-commit.log
[18551 ms] postCreateCommand failed with exit code 1. Skipping any further user-provided commands.`

**Comment by pamelafox** [comment]
Did you do a git clone when opening it up? Or did you perhaps download the zip and open it up that way?

You could remove "pre-commit install" from devcontainer.json:
https://github.com/pamelafox/simple-fastapi-container/blob/main/.devcontainer/devcontainer.json#L45

That command assumes you're in a git repo, as it sets up pre-commit hooks.

**Comment by MiguelElGallo** [comment]
Hi,
Yeah, I was guessing it is pre-commit.
I did a clone, which is why I thought it should work.
I removed pre-commit and it works.
Cheers!
