### ISSUE TITLE
README issues 

### ISSUE THREAD

**Issue by ChenxiJiang333** [pamelafox/simple-fastapi-container#7]
1.
**Describe the issue:** 
The port is incorrect.
![Screenshot 2023-04-13 134624](https://user-images.githubusercontent.com/119990644/231665926-acddb5e7-d93e-4adf-835f-ae4131f3da3e.png)

**Suggestion:** Update to `3100`.

2.
**Describe the issue:** 
`failed to read dockerfile` error occurs when execute the command below, for the Dockerfile is actually in the `src` folder. 
![Screenshot 2023-04-13 135849](https://user-images.githubusercontent.com/119990644/231667691-211f7589-2323-4e14-a9f1-763cde4d29f2.png)

**Suggestion:**
 Add a step `cd src`, or update the command to `docker build --tag fastapi-app .\src` .

3. 
**Describe the issue:** 
Miss the option `--template` .
![Screenshot 2023-04-13 141525](https://user-images.githubusercontent.com/119990644/231672097-7f5f17f1-bdd7-42a4-86e5-f39c9ac4f7eb.png)

**Suggestion:**
Please provide the `--template` option, update to `azd init --template pamelafox/simple-fastapi-container `

@pamelafox for notification.

**Comment by pamelafox** [comment]
Thanks! Please see my PR at https://github.com/pamelafox/simple-fastapi-container/pull/8
I made the same change I discussed in the other review - removing `azd init` in favor of `azd auth login`, to match the flow of checking out the code first.

**Comment by v-xuto** [comment]
@pamelafox I think the modification in https://github.com/pamelafox/simple-fastapi-container/pull/8 is fine.

**Comment by pamelafox** [comment]
Great, merged
